import{describe,expect,it}from'vitest';
import{TRANSITIONS,evaluateTransition,normalizeDeadline,isOverdue}from'../../src/service/commitment-lifecycle-service.js';
const valid={securitySafe:true,identityResolved:true,origin:'human',partyResolved:true,evidenceVerified:true,scopeValid:true,versionMatches:true,leaseValid:true,fencingValid:true};
describe('protected commitment lifecycle and deadlines',()=>{
	it('has finite terminal-safe transitions',()=>{expect(TRANSITIONS).toMatchObject({candidate:['inconclusive','active','cancelled','disputed'],active:['fulfilled','overdue','cancelled','superseded','disputed'],fulfilled:[],cancelled:[],superseded:[]});expect(evaluateTransition({from:'fulfilled',to:'active',...valid})).toMatchObject({allowed:false,reason:'commitment_transition_invalid'});});
	it('requires verified human evidence for activation and terminal changes',()=>{expect(evaluateTransition({from:'candidate',to:'active',...valid}).allowed).toBe(true);expect(evaluateTransition({from:'candidate',to:'active',...valid,origin:'automated_system'}).allowed).toBe(false);expect(evaluateTransition({from:'active',to:'fulfilled',...valid,evidenceVerified:false}).reason).toBe('commitment_terminal_evidence_required');});
	it('rejects cross-scope version conflicts and stale fencing',()=>{expect(evaluateTransition({from:'candidate',to:'active',...valid,scopeValid:false}).reason).toBe('commitment_scope_mismatch');expect(evaluateTransition({from:'candidate',to:'active',...valid,versionMatches:false}).reason).toBe('commitment_version_conflict');expect(evaluateTransition({from:'candidate',to:'active',...valid,fencingValid:false}).reason).toBe('commitment_stale_worker');});
	it('normalizes exact and relative deadlines without inventing precision',()=>{expect(normalizeDeadline('tomorrow',{observedAt:'2026-01-15T12:00:00Z',timezone:'America/Toronto'})).toMatchObject({type:'relative',precision:'day',needsReview:false});expect(normalizeDeadline('ASAP')).toMatchObject({type:'ambiguous',precision:'ambiguous',start:null,needsReview:true});expect(normalizeDeadline('tomorrow',{observedAt:'2026-01-15T12:00:00Z'}).needsReview).toBe(true);});
	it('makes overdue processing state and deadline aware',()=>{expect(isOverdue({state:'active',deadlineState:'current',normalizedEnd:'2020-01-01T00:00:00Z'})).toBe(true);expect(isOverdue({state:'cancelled',deadlineState:'current',normalizedEnd:'2020-01-01T00:00:00Z'})).toBe(false);expect(isOverdue({state:'active',deadlineState:'cancelled',normalizedEnd:'2020-01-01T00:00:00Z'})).toBe(false);});
	it('resolves terminal races deterministically through expected version',()=>{const fulfilled=evaluateTransition({from:'active',to:'fulfilled',...valid,versionMatches:true});const cancelledAfterLostRace=evaluateTransition({from:'active',to:'cancelled',...valid,versionMatches:false});expect(fulfilled.allowed).toBe(true);expect(cancelledAfterLostRace).toMatchObject({allowed:false,reason:'commitment_version_conflict'});});
	it('never permits automated, unknown-party, unsafe, or confidence-only activation',()=>{for(const patch of [{origin:'automated_system'},{partyResolved:false},{securitySafe:false},{identityResolved:false},{evidenceVerified:false}])expect(evaluateTransition({from:'candidate',to:'active',...valid,...patch}).allowed).toBe(false);});
});
