import {describe,expect,it} from 'vitest'; import {validateLocalEvidence,finalizePolicy,evidenceIdentity,decisionIdentity} from '../../src/service/hybrid-mail-intelligence-service.js';
const valid={contractVersion:'local-mail-semantic-evidence-v1',promptVersion:'apple-mail-evidence-p0-v1',inferenceMode:'apple_on_device',modelFamily:'apple-system-language-model',osVersion:'iOS 27.0',language:'en-CA',generatedAt:new Date().toISOString(),messageVersion:2,contentDigest:'a'.repeat(64),intentCandidate:'inform',eventCandidate:'transaction',financialSubtypeCandidate:'financial_transaction',marketingSubtypeCandidate:'none',actionabilityCandidate:'none',certainty:82,availabilityState:'available',ambiguous:false,conflicting:false};
describe('hybrid apple mail evidence',()=>{
 it('accepts bounded structured evidence without final state fields',()=>{expect(validateLocalEvidence(valid)).toEqual({valid:true,errors:[]});expect(valid).not.toHaveProperty('category');expect(valid).not.toHaveProperty('isPriority');});
	 it('rejects all free-text evidence fields at the boundary',()=>{for(const key of ['deadlineCandidate','entityCandidates','supportingSemanticCues','explanation'])expect(validateLocalEvidence({...valid,[key]:'private value'}).errors).toContain('unknown_field_rejected');});
	 it('issues a new append-only evidence and decision generation after expiry renewal',async()=>{const target={actorUserId:7,workspaceId:8,accountId:9,messageId:10};const first=await evidenceIdentity({...target,evidence:{...valid,generatedAt:'2026-07-12T12:00:00.000Z'}});const renewed=await evidenceIdentity({...target,evidence:{...valid,generatedAt:'2026-07-13T13:00:00.000Z'}});expect(renewed).not.toBe(first);expect(await decisionIdentity(renewed)).not.toBe(await decisionIdentity(first));});
 it('rejects stale, malformed, provider-spoofed, and unknown-field evidence',()=>{expect(validateLocalEvidence({...valid,modelFamily:'cloud-model'}).valid).toBe(false);expect(validateLocalEvidence({...valid,generatedAt:'2020-01-01T00:00:00Z'}).valid).toBe(false);expect(validateLocalEvidence({...valid,contentDigest:'raw body'}).valid).toBe(false);expect(validateLocalEvidence({...valid,rawBody:'secret'}).errors).toContain('unknown_field_rejected');});
 it('keeps manual category while preserving non-bypassable priority hard gates',()=>expect(finalizePolicy({deterministic:{securityVerdict:'unsafe',marketingHardGate:true},local:valid,manualOverride:{category:'work',is_priority:true}})).toMatchObject({category:'work',is_priority:false,decision_state:'needs_review'}));
 it('prevents Apple output from bypassing marketing and security hard gates',()=>{expect(finalizePolicy({deterministic:{securityVerdict:'safe',marketingHardGate:true,marketingCategory:'financial_marketing',actionRequired:true},local:{...valid,marketingSubtypeCandidate:'none'}})).toMatchObject({category:'financial_marketing',is_priority:false});expect(finalizePolicy({deterministic:{securityVerdict:'unknown',financialSecurity:true},local:valid})).toMatchObject({is_priority:false,decision_state:'needs_review'});});
 it('abstains on disagreement instead of latest-result-wins',()=>expect(finalizePolicy({deterministic:{securityVerdict:'safe',financialSubtype:'financial_statement'},local:{...valid,financialSubtypeCandidate:'financial_transaction'}})).toMatchObject({decision_state:'conflicted',is_priority:false}));
});
